name: emoji_finder
description: "This package will help you check if an emoji is used in your text without hardcoding(e.g. \uFE0F)."
version: 0.0.1
repository: https://github.com/Bakbongdo/emoji_finder.git

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
